Nicer error message if missing configuration
Wraps the error to give a bit more context, from this:

❯ gh slack auth
Error: could not find key "extensions"

To:

❯ gh slack auth
Error: failed to read gh-slack configuration: could not find key "extensions"